---
title: Learning Programming2
author: 'Arjun Chakrawal'
output: html_document
date: '2019-04-14'
slug: bla
categories:
  - R
tags:
  - Academic
  - R Markdown
  - Demo
image:
  caption: Snapshot
  focal_point: Smart

links:
- icon: linkedin
  icon_pack: fab
  name: Follow
  url: https://www.linkedin.com/in/arjun-chakrawal/

# slides: newslides/example-slides2
summary: Some attempts to learning R, Python and Matlab.
url_code: ""
url_pdf: ""
url_slides: ""
url_video: "" 
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)
library(reticulate)
use_python('C:\\Users\\arch9809\\AppData\\Local\\Continuum\\anaconda3')
library(ggplot2)
library(reshape2)
library(plotly)
library(latex2exp)
```

## Day 2 (R plot and ggplot2): 
Data Source 
https://bolin.su.se/data/stockholm/files/stockholm-historical-weather-observations-2017/temperature/daily/raw/stockholm_daily_temp_obs_2013_2017_t1t2t3txtntm.txt 
```{r}
textFile <- 'https://bolin.su.se/data/stockholm/files/stockholm-historical-weather-observations-2017/temperature/daily/raw/stockholm_daily_temp_obs_2013_2017_t1t2t3txtntm.txt'

temp_Data <- basename(textFile)
if (!file.exists(temp_Data)) {
  download.file(textFile, temp_Data)
}
temp_Data = read.table(temp_Data, header=FALSE)
names(temp_Data) = c('year', 'month', 'day', 'morn', 'noon', 'eve','tmax', 'tmin', 'tmean')
head(temp_Data)
```

### Plotting data

```{r}
plot(temp_Data$noon)
x=1:nrow(temp_Data);y=temp_Data$noon
qplot(x,y,geom='point')
```

```{r}
plot(temp_Data$noon, type='l')
x=1:nrow(temp_Data);y=temp_Data$noon
qplot(x,y,geom='line')
```
```{r}
plot(temp_Data$noon, type = 'b')
qplot(x, y , geom = c('point', 'line'))
```

###  R plot

```{r}
dates=strptime(x=paste(temp_Data$year,temp_Data$month,temp_Data$day,sep=' '),format='%Y %m %d')
temp_Data$time = as.Date(dates)

plot(temp_Data$time, temp_Data$morn, ylim=c(-15,35),type = 'b')
points(temp_Data$time, temp_Data$noon, type = 'b', col=2)
points(temp_Data$time, temp_Data$eve, type = 'b', col=3)
legend('topright', inset=0.02, col=c(1,2,3), lwd=3,c('noon', 'morning', 'evening'), bty='n')
```

###  ggplot2

```{r}
morn_noon_eve=temp_Data[,c('morn','noon','eve','time')]
data_melt=melt(morn_noon_eve,id='time')
ggplot(data_melt)+geom_point(aes(x=time, y=value, color=variable, group=variable),na.rm=TRUE)+
  geom_line(aes(x=time,y=value,colour=variable,group=variable),na.rm=TRUE)
```

### Fancy plot: theme_bw

```{r}
ggplot(data_melt)+geom_point(aes(x=time, y=value, color=variable, group=variable),na.rm=TRUE)+
  geom_line(aes(x=time,y=value,colour=variable,group=variable),na.rm=TRUE)+
  scale_x_date(date_breaks = '1 year', date_labels='%Y')+
  scale_color_manual(labels=c('Morning','Noon','Evening'),values=c('#1b9e77','#d95f02','#7570b3'))+
  labs(title = 'First ggplot', color='Observation\ntime')+
  xlab('Time (year)')+
  ylab(expression(paste('Temperature T [',degree,'C]',sep='')))+
  theme_bw(14)+
  theme(legend.title = element_text(face = 'bold', size = 14), plot.title = element_text(hjust = 0.5, size=16, face = 'bold'))
```

### Fancy plot: theme_dark 

### To find other avilable theme press f1 key near theme.

```{r}
ggplot(data_melt)+geom_point(aes(x=time, y=value, color=variable, group=variable),na.rm=TRUE)+
  geom_line(aes(x=time,y=value,colour=variable,group=variable),na.rm=TRUE)+
  scale_x_date(date_breaks = '1 year', date_labels='%Y')+
  scale_color_manual(labels=c('Morning','Noon','Evening'),values=c('#1b9e77','#d95f02','#7570b3'))+
  labs(title = 'First ggplot', color='Observation\ntime')+
  xlab('Time (year)')+
  ylab(expression(paste('Temperature T [',degree,'C]',sep='')))+
  theme_dark(14)+
  theme(legend.title = element_text(face = 'bold', size = 14), plot.title = element_text(hjust = 0.5, size=16, face = 'bold'))
```

### Plotting distributions (ggplot2)

```{r}
ggplot(data_melt, aes(x=value))+
  geom_histogram(aes(y=..density..),binwidth=.5,colour='black', fill='white',na.rm = TRUE)+
  labs(title = 'Plotting distributions', color='Observation\ntime')+
  xlab(expression(paste('Temperature T [',degree,'C]',sep='')))+
  ylab('Density')+
  theme_bw(14)+ theme(plot.title = element_text(hjust = 0.5, size=16, face = 'bold'))
```

```{r}
ggplot(data_melt, aes(x=value))+
  geom_density(aes(group=variable,color=variable,fill=variable),alpha=.2,na.rm = TRUE) + 
  labs(title = 'Plotting distributions', color='Observation\ntime')+
  xlab(expression(paste('Temperature T [',degree,'C]',sep='')))+
  ylab('Density')+
  theme_bw(14)+ theme(plot.title = element_text(hjust = 0.5, size=16, face = 'bold'))
```

```{r}
g= ggplot(data_melt,aes(x=variable, y=value,fill=variable))+
  geom_boxplot(na.rm = TRUE)+ 
  labs(title = 'Plotting Boxplots', color='Observation\ntime')+
  xlab('')+
  ylab(expression(paste('Temperature T [',degree,'C]',sep='')))+
  theme_minimal(14)+ theme(plot.title = element_text(hjust = 0.5, size=16, face = 'bold'))
g
g= ggplot(data_melt,aes(x=variable, y=value,fill=variable))+
  geom_boxplot(na.rm = TRUE)+
  xlab('')+labs(title = 'Plotting Boxplots', color='Observation\ntime')+
  theme_minimal(14)+ theme(plot.title = element_text(hjust = 0.5, size=16, face = 'bold'))
g= ggplotly(g)
layout(g, yaxis = list(title = 'Temperature [C]'))
```


### Plotting ribbons (ggplot2)

```{r}
min_max_meanT=temp_Data[,c('tmin', 'tmax', 'tmean','time')]
head(min_max_meanT)

h= ggplot(min_max_meanT, aes(x=time))+
  geom_ribbon(aes(ymin = min_max_meanT$tmin, ymax = min_max_meanT$tmax), fill = "grey50",na.rm = TRUE)+
  geom_line(aes(y=min_max_meanT$tmean),color='#2b8cbe')+
    scale_x_date(date_breaks = '1 year', date_labels='%Y')+
  labs(title = 'Plotting min_max_meanT', color='Temperature')+
  xlab('Date')+
  ylab(expression(paste('Temperature T [',degree,'C]',sep='')))+
  theme_gray(14)+ theme(legend.title = element_text(face = 'bold', size = 14),legend.position='bottom',plot.title = element_text(hjust = 0.5, size=16, face = 'bold'))
h
```
